package com.sky.service;

import com.sky.context.BaseContext;
import com.sky.controller.admin.DishController;
import com.sky.controller.user.AddressBookController;
import com.sky.entity.AddressBook;
import com.sky.entity.Dish;
import com.sky.exception.BaseException;
import com.sky.handler.GlobalExceptionHandler;
import com.sky.mapper.AddressBookMapper;
import com.sky.mapper.DishMapper;
import com.sky.service.impl.AddressBookServiceImpl;
import com.sky.service.impl.DIshServiceImpl;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.SqlSessionFactoryBean;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.http.MediaType;
import org.springframework.transaction.annotation.AnnotationTransactionAttributeSource;
import org.springframework.transaction.interceptor.TransactionInterceptor;
import org.springframework.transaction.support.TransactionTemplate;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.AdditionalAnswers.delegatesTo;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/** 真实执行 Mapper 和 Spring 事务，但仅使用每个测试独立的 H2 内存数据库。 */
class BackendHardeningSqlTest {
    private EmbeddedDatabase database;
    private JdbcTemplate jdbc;
    private AddressBookMapper addresses;
    private AddressBookService addressService;
    private DishService dishService;
    private DataSourceTransactionManager transactionManager;
    private RedisTemplate redis;

    @BeforeEach
    void setUp() throws Exception {
        database = new EmbeddedDatabaseBuilder().generateUniqueName(true)
                .setType(EmbeddedDatabaseType.H2).build();
        jdbc = new JdbcTemplate(database);
        jdbc.execute("CREATE TABLE address_book (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY, "
                + "user_id BIGINT, consignee VARCHAR(50), phone VARCHAR(50), sex VARCHAR(10), "
                + "province_code VARCHAR(50), province_name VARCHAR(50), city_code VARCHAR(50), "
                + "city_name VARCHAR(50), district_code VARCHAR(50), district_name VARCHAR(50), "
                + "detail VARCHAR(100), label VARCHAR(50), is_default INT)");
        jdbc.execute("CREATE TABLE dish (id BIGINT PRIMARY KEY, category_id BIGINT, status INT, "
                + "name VARCHAR(50), price DECIMAL(10,2), image VARCHAR(100), description VARCHAR(100))");
        jdbc.update("INSERT INTO address_book(id,user_id,detail,is_default) VALUES(1,7,'mine',1),(2,7,'second',0),(3,8,'other',1)");
        jdbc.update("INSERT INTO dish(id,category_id,status,name,price) VALUES(10,20,1,'noodles',15)");
        SqlSessionFactoryBean factory = new SqlSessionFactoryBean();
        factory.setDataSource(database);
        factory.setTypeAliasesPackage("com.sky.entity,com.sky.vo");
        factory.setMapperLocations(new ClassPathResource("mapper/AddressBookMapper.xml"),
                new ClassPathResource("mapper/DishMapper.xml"));
        org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
        configuration.setMapUnderscoreToCamelCase(true);
        factory.setConfiguration(configuration);
        SqlSessionTemplate session = new SqlSessionTemplate(factory.getObject());
        addresses = session.getMapper(AddressBookMapper.class);
        transactionManager = new DataSourceTransactionManager(database);
        addressService = addressService(addresses);
        DIshServiceImpl dishes = new DIshServiceImpl();
        redis = mock(RedisTemplate.class);
        ReflectionTestUtils.setField(dishes, "dishMapper", session.getMapper(DishMapper.class));
        ReflectionTestUtils.setField(dishes, "redisTemplate", redis);
        dishService = (DishService) transactional(dishes);
        BaseContext.setCurrentId(7L);
    }

    @AfterEach
    void tearDown() {
        BaseContext.removeCurrentId();
        if (database != null) database.shutdown();
    }

    @Test
    void addressHttpEndpointsRejectForeignIdsAndForgedOwner() throws Exception {
        AddressBookController controller = new AddressBookController();
        ReflectionTestUtils.setField(controller, "addressBookService", addressService);
        MockMvc mvc = MockMvcBuilders.standaloneSetup(controller)
                .setControllerAdvice(new GlobalExceptionHandler()).build();
        mvc.perform(get("/user/addressBook/3"))
                .andExpect(status().isOk()).andExpect(jsonPath("$.code").value(0));
        mvc.perform(put("/user/addressBook").contentType(MediaType.APPLICATION_JSON)
                        .content("{\"id\":3,\"userId\":8,\"detail\":\"tampered\"}"))
                .andExpect(status().isOk()).andExpect(jsonPath("$.code").value(0));
        mvc.perform(delete("/user/addressBook").param("id", "3"))
                .andExpect(status().isOk()).andExpect(jsonPath("$.code").value(0));
        mvc.perform(put("/user/addressBook/default").contentType(MediaType.APPLICATION_JSON)
                        .content("{\"id\":3,\"userId\":8}"))
                .andExpect(status().isOk()).andExpect(jsonPath("$.code").value(0));
        assertEquals("other", jdbc.queryForObject("SELECT detail FROM address_book WHERE id=3", String.class));
        assertEquals(1, defaultFlag(1));
    }

    @Test
    void dishHttpEndpointWorksWithOnlyIdAndIgnoresInjectedFields() throws Exception {
        DishController controller = new DishController();
        ReflectionTestUtils.setField(controller, "dishService", dishService);
        MockMvc mvc = MockMvcBuilders.standaloneSetup(controller)
                .setControllerAdvice(new GlobalExceptionHandler()).build();
        mvc.perform(post("/admin/dish/status/0").param("id", "10"))
                .andExpect(status().isOk()).andExpect(jsonPath("$.code").value(1));
        verify(redis).delete("dish_category_20");
        assertEquals(0, jdbc.queryForObject("SELECT status FROM dish WHERE id=10", Integer.class));
        mvc.perform(post("/admin/dish/status/1").param("id", "10")
                        .param("categoryId", "999").param("name", "tampered").param("price", "0"))
                .andExpect(status().isOk()).andExpect(jsonPath("$.code").value(1));
        assertEquals(20L, jdbc.queryForObject("SELECT category_id FROM dish WHERE id=10", Long.class));
        assertEquals("noodles", jdbc.queryForObject("SELECT name FROM dish WHERE id=10", String.class));
        assertEquals(1, jdbc.queryForObject("SELECT status FROM dish WHERE id=10", Integer.class));
    }

    @Test
    void foreignAddressCannotBeReadEditedDeletedOrMadeDefault() {
        assertThrows(BaseException.class, () -> addressService.getById(3L));
        assertThrows(BaseException.class, () -> addressService.update(
                AddressBook.builder().id(3L).userId(8L).detail("tampered").build()));
        assertThrows(BaseException.class, () -> addressService.deleteById(3L));
        assertThrows(BaseException.class, () -> addressService.setDefault(AddressBook.builder().id(3L).build()));
        assertEquals("other", jdbc.queryForObject("SELECT detail FROM address_book WHERE id=3", String.class));
        assertEquals(1, defaultFlag(1));
        assertEquals(1, defaultFlag(3));
    }

    @Test
    void mapperMutationsEnforceOwnershipEvenWithoutServicePrecheck() {
        assertNull(addresses.getOwnedById(3L, 7L));
        assertEquals(0, addresses.update(AddressBook.builder().id(3L).userId(7L).detail("tampered").build()));
        assertEquals(0, addresses.deleteOwnedById(3L, 7L));
        assertEquals("other", jdbc.queryForObject("SELECT detail FROM address_book WHERE id=3", String.class));
    }

    @Test
    void listAndSaveAlwaysUseAuthenticatedOwner() {
        assertEquals(2, addressService.list(AddressBook.builder().userId(8L).build()).size());
        addressService.save(AddressBook.builder().userId(8L).detail("new").isDefault(1).build());
        assertEquals(7L, jdbc.queryForObject("SELECT user_id FROM address_book WHERE detail='new'", Long.class));
        assertEquals(0, jdbc.queryForObject("SELECT is_default FROM address_book WHERE detail='new'", Integer.class));
    }

    @Test
    void ownerCanEditAndDeleteWithoutChangingDefaultOrOwnership() {
        addressService.update(AddressBook.builder().id(2L).userId(8L).detail("edited").isDefault(1).build());
        assertEquals("edited", addressService.getById(2L).getDetail());
        assertEquals(7L, addressService.getById(2L).getUserId());
        assertEquals(0, defaultFlag(2));
        // 空编辑和重复编辑均可安全返回。
        addressService.update(AddressBook.builder().id(2L).isDefault(1).build());
        addressService.update(AddressBook.builder().id(2L).detail("edited").build());
        addressService.deleteById(2L);
        assertNull(addresses.getOwnedById(2L, 7L));
    }

    @Test
    void ownerCanEditCompleteRegionSnapshot() {
        addressService.update(AddressBook.builder().id(2L)
                .provinceCode("44").provinceName("广东省")
                .cityCode("4401").cityName("广州市")
                .districtCode("440106").districtName("天河区")
                .detail("体育西路 1 号").build());

        AddressBook updated = addressService.getById(2L);
        assertEquals("44", updated.getProvinceCode());
        assertEquals("广东省", updated.getProvinceName());
        assertEquals("4401", updated.getCityCode());
        assertEquals("广州市", updated.getCityName());
        assertEquals("440106", updated.getDistrictCode());
        assertEquals("天河区", updated.getDistrictName());
        assertEquals("体育西路 1 号", updated.getDetail());
    }

    @Test
    void defaultSwitchUpdatesOnlyDefaultFlagOfOwnedAddresses() {
        addressService.setDefault(AddressBook.builder().id(2L).userId(8L).detail("tampered").build());
        assertEquals(0, defaultFlag(1));
        assertEquals(1, defaultFlag(2));
        assertEquals(1, defaultFlag(3));
        assertEquals("second", addressService.getById(2L).getDetail());
        addressService.setDefault(AddressBook.builder().id(2L).build());
        assertEquals(1, defaultFlag(2));
    }

    @Test
    void failedDefaultTargetWriteRollsBackClearingPreviousDefault() {
        AddressBookMapper failing = mock(AddressBookMapper.class, delegatesTo(addresses));
        doReturn(0).when(failing).update(any(AddressBook.class));
        AddressBookService service = addressService(failing);
        assertThrows(BaseException.class, () -> service.setDefault(AddressBook.builder().id(2L).build()));
        assertEquals(1, defaultFlag(1));
        assertEquals(0, defaultFlag(2));
    }

    @Test
    void missingIdentityAndMissingAddressesFailClosed() {
        assertThrows(BaseException.class, () -> addressService.getById(999L));
        assertThrows(BaseException.class, () -> addressService.deleteById(null));
        BaseContext.removeCurrentId();
        assertThrows(BaseException.class, () -> addressService.list(new AddressBook()));
        assertThrows(BaseException.class, () -> addressService.save(new AddressBook()));
        assertThrows(BaseException.class, () -> addressService.getById(1L));
        assertThrows(BaseException.class, () -> addressService.update(AddressBook.builder().id(1L).build()));
        assertThrows(BaseException.class, () -> addressService.setDefault(AddressBook.builder().id(2L).build()));
        assertThrows(BaseException.class, () -> addressService.deleteById(1L));
    }

    @Test
    void dishStatusOnlyChangesStatusAndEvictsPersistedCategoryAfterCommit() {
        new TransactionTemplate(transactionManager).executeWithoutResult(status -> {
            dishService.statusUpdateDish(Dish.builder().id(10L).categoryId(999L).status(0)
                    .name("tampered").price(java.math.BigDecimal.ZERO).build());
            verifyNoInteractions(redis);
            assertEquals(0, jdbc.queryForObject("SELECT status FROM dish WHERE id=10", Integer.class));
        });
        verify(redis).delete("dish_category_20");
        verifyNoMoreInteractions(redis);
        assertEquals(20L, jdbc.queryForObject("SELECT category_id FROM dish WHERE id=10", Long.class));
        assertEquals("noodles", jdbc.queryForObject("SELECT name FROM dish WHERE id=10", String.class));
        dishService.statusUpdateDish(Dish.builder().id(10L).status(1).build());
        assertEquals(1, jdbc.queryForObject("SELECT status FROM dish WHERE id=10", Integer.class));
    }

    @Test
    void dishRollbackDoesNotEvictCacheAndKeepsOriginalStatus() {
        new TransactionTemplate(transactionManager).executeWithoutResult(status -> {
            dishService.statusUpdateDish(Dish.builder().id(10L).status(0).build());
            status.setRollbackOnly();
        });
        assertEquals(1, jdbc.queryForObject("SELECT status FROM dish WHERE id=10", Integer.class));
        verifyNoInteractions(redis);
    }

    @Test
    void invalidOrMissingDishDoesNotMutateOrEvict() {
        assertThrows(BaseException.class, () -> dishService.statusUpdateDish(Dish.builder().id(10L).status(2).build()));
        assertThrows(BaseException.class, () -> dishService.statusUpdateDish(Dish.builder().status(0).build()));
        assertThrows(BaseException.class, () -> dishService.statusUpdateDish(Dish.builder().id(999L).status(0).build()));
        verifyNoInteractions(redis);
        assertEquals(1, jdbc.queryForObject("SELECT status FROM dish WHERE id=10", Integer.class));
    }

    private int defaultFlag(long id) {
        return jdbc.queryForObject("SELECT is_default FROM address_book WHERE id=?", Integer.class, id);
    }

    private AddressBookService addressService(AddressBookMapper mapper) {
        AddressBookServiceImpl service = new AddressBookServiceImpl();
        ReflectionTestUtils.setField(service, "addressBookMapper", mapper);
        return (AddressBookService) transactional(service);
    }

    private Object transactional(Object target) {
        ProxyFactory proxy = new ProxyFactory(target);
        proxy.addAdvice(new TransactionInterceptor(transactionManager, new AnnotationTransactionAttributeSource()));
        return proxy.getProxy();
    }
}
